import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

export default function Home() {

  const handleFormSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const data = new FormData(e.currentTarget);

    const sentData = {
      name: data.get('name'),
      address: data.get('address'),
      email: data.get('email'),
      birthday: data.get('birthday'),
    }

    const JSONdata = JSON.stringify(sentData);

    const endpoint = 'https://ewx1dutd3a.execute-api.ap-southeast-2.amazonaws.com/internal-testing/huh'

    const options = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSONdata,
    }

    const response = await fetch(endpoint, options)

    const result = await response.json()

    console.log(result);

  }
  return (
    <>
      <Head>
        <title>Some random tings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form className={styles["content-form"]} onSubmit={handleFormSubmit}>

          <label htmlFor="name">
            Full name
          </label>
          <input type="text" id="name" name="name" />

          <label htmlFor="address">
            Address
          </label>
          <input type="text" id="address" name="address" />

          <label htmlFor="email">
            Email
          </label>
          <input type="text" id="email" name="email" />

          <label htmlFor="birthday">Birthday</label>
          <input
            type="date"
            id="birthday"
            name="birthday"
          />

          <label htmlFor="profile">Profile Picture</label>
          <input type="file" id="profile" name="profile" />

          <input type="submit" value="Submit" />
        </form>
      </main>
    </>
  );
}
